controllers:
    resource: ../src/Controller/
    type: attribute

index:
    path: /
    controller: App\Controller\IndexController::index 

index_unifi:
    path: /guest/s/default/
    controller: App\Controller\IndexController::index 

login:
    path: login
    controller: App\Controller\LoginController::index 

logout:
    path: logout
    controller: App\Controller\LogoutController::index 

return_callback:
    path: /return/callback
    controller: App\Controller\ReturnCallbackController::index 
